schema_version = "1.0.0"
id = "jd_miter_box_forked"
name = "Miter Box (Forked)"
version = "0.0.9"
tagline = "Forked and updated for Blender 4.x"
maintainer = "Jo√£o Desager / (Shibazo)"
type = "add-on"
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/shibazo/JD-Miter-Box-Forked"
